env:
    # Duplicate these from environment to avoid
    # need to pass them to every kubernetes command
    ukb_app_id: "41430"
    gcs_bucket: "rs-ukb"
    gcp_project: "uk-biobank-279813"
    gke_io_ncpu: 8
raw:
    plink:
        contigs:
            # For UKB chromosome codes, see:
            # https://biobank.ndph.ox.ac.uk/showcase/refer.cgi?id=531
            # "numeric chromosome label 1-26; 23=X,24=Y,25=XY,26=MT"
            - {index: 0, code: 1, name: 1}
            - {index: 1, code: 2, name: 2}
            - {index: 2, code: 3, name: 3}
            - {index: 3, code: 4, name: 4}
            - {index: 4, code: 5, name: 5}
            - {index: 5, code: 6, name: 6}
            - {index: 6, code: 7, name: 7}
            - {index: 7, code: 8, name: 8}
            - {index: 8, code: 9, name: 9}
            - {index: 9, code: 10, name: 10}
            - {index: 10, code: 11, name: 11}
            - {index: 11, code: 12, name: 12}
            - {index: 12, code: 13, name: 13}
            - {index: 13, code: 14, name: 14}
            - {index: 14, code: 15, name: 15}
            - {index: 15, code: 16, name: 16}
            - {index: 16, code: 17, name: 17}
            - {index: 17, code: 18, name: 18}
            - {index: 18, code: 19, name: 19}
            - {index: 19, code: 20, name: 20}
            - {index: 20, code: 21, name: 21}
            - {index: 21, code: 22, name: 22}
            - {index: 22, code: 23, name: X}
            - {index: 23, code: 24, name: Y}
            - {index: 24, code: 25, name: XY}
            - {index: 25, code: 26, name: MT}
    bgen:
        contigs:
            # Same as PLINK w/o Y and MT
            # See http://biobank.ctsu.ox.ac.uk/crystal/label.cgi?id=263 for 
            # details on `n_consent_samples` which is "number of linked samples 
            # (i.e.currently consenting participants) in dataset" used in
            # .sample file names. To find number of variants, use:
            # for f in `gsutil ls gs://rs-ukb/raw-data/gt-imputation/*.txt`; do 
            # echo $f `gsutil cat $f | wc -l`; done
            - {index: 0, code: 1, name: 1, n_consent_samples: 487296, n_variants: 7402791}
            - {index: 1, code: 2, name: 2, n_consent_samples: 487296, n_variants: 8129063}
            - {index: 2, code: 3, name: 3, n_consent_samples: 487296, n_variants: 6696680}
            - {index: 3, code: 4, name: 4, n_consent_samples: 487296, n_variants: 6555871}
            - {index: 4, code: 5, name: 5, n_consent_samples: 487296, n_variants: 6070641}
            - {index: 5, code: 6, name: 6, n_consent_samples: 487296, n_variants: 5751712}
            - {index: 6, code: 7, name: 7, n_consent_samples: 487296, n_variants: 5405524}
            - {index: 7, code: 8, name: 8, n_consent_samples: 487296, n_variants: 5282223}
            - {index: 8, code: 9, name: 9, n_consent_samples: 487296, n_variants: 4066774}
            - {index: 9, code: 10, name: 10, n_consent_samples: 487296, n_variants: 4562904}
            - {index: 10, code: 11, name: 11, n_consent_samples: 487296, n_variants: 4628348}
            - {index: 11, code: 12, name: 12, n_consent_samples: 487296, n_variants: 4431052}
            - {index: 12, code: 13, name: 13, n_consent_samples: 487296, n_variants: 3270217}
            - {index: 13, code: 14, name: 14, n_consent_samples: 487296, n_variants: 3037521}
            - {index: 14, code: 15, name: 15, n_consent_samples: 487296, n_variants: 2767971}
            - {index: 15, code: 16, name: 16, n_consent_samples: 487296, n_variants: 3089612}
            - {index: 16, code: 17, name: 17, n_consent_samples: 487296, n_variants: 2660711}
            - {index: 17, code: 18, name: 18, n_consent_samples: 487296, n_variants: 2599579}
            - {index: 18, code: 19, name: 19, n_consent_samples: 487296, n_variants: 2087017}
            - {index: 19, code: 20, name: 20, n_consent_samples: 487296, n_variants: 2082571}
            - {index: 20, code: 21, name: 21, n_consent_samples: 487296, n_variants: 1261158}
            - {index: 21, code: 22, name: 22, n_consent_samples: 487296, n_variants: 1255683}
            - {index: 22, code: 23, name: X, n_consent_samples: 486645, n_variants: 3917799}
            - {index: 24, code: 25, name: XY, n_consent_samples: 486331, n_variants: 45906}