#cloud-config
groups:
- docker
packages:
- apt-transport-https
- ca-certificates
- curl
- gnupg-agent
- software-properties-common
- ubuntu-drivers-common
runcmd:
- curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
- add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release
  -cs) stable"
- apt-get update -y
- apt-get install -y docker-ce docker-ce-cli containerd.io
- systemctl start docker
- systemctl enable docker
- docker run --net=host   -e PUBLIC_INGRESS=False eczech/ukb-gwas-pipeline-nealelab:v2020.12.0
  dask-scheduler --version
- curl -sSO https://dl.google.com/cloudagents/add-monitoring-agent-repo.sh
- bash add-monitoring-agent-repo.sh
- apt-get update -y
- apt-get install -y stackdriver-agent
- service stackdriver-agent start
system_info:
  default_user:
    groups:
    - docker
write_files:
- content: 'net.ipv4.conf.all.forwarding=1

    '
  path: /etc/sysctl.d/enabled_ipv4_forwarding.conf

