#cloud-config

# Bootstrap
packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common
  - ubuntu-drivers-common

# Enable ipv4 forwarding, required on CIS hardened machines
write_files:
  - path: /etc/sysctl.d/enabled_ipv4_forwarding.conf
    content: |
      net.ipv4.conf.all.forwarding=1

# create the docker group
groups:
  - docker

# Add default auto created user to docker group
system_info:
  default_user:
    groups: [docker]


runcmd:
  # Install Docker
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
  - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - apt-get update -y
  - apt-get install -y docker-ce docker-ce-cli containerd.io
  - systemctl start docker
  - systemctl enable docker
  # Run container
  - 'docker run --net=host   -e PUBLIC_INGRESS=False  -e EXTRA_CONDA_PACKAGES="python==3.8.0 numpy==1.18.1 distributed==2.30.0 tornado==6.0.4 dask==2.30.0 xarray==0.16.1 tini==0.18.0 lz4==3.1.0 cytoolz==0.11.0 nomkl==1.0 zarr==2.4.0 pandas==1.0.1 python-blosc==1.9.2 dask-ml==1.7.0 gcsfs==0.7.1 fire==0.3.1 numba==0.51.2 pyarrow==2.0.0 -c conda-forge"  -e EXTRA_PIP_PACKAGES="cbgen==0.1.6 rechunker==0.3.1 bed-reader==0.1.1 git+https://github.com/pystatgen/sgkit.git@c5548821653fa2759421668092716d2036834ffe#egg=sgkit" daskdev/dask:2.30.0 dask-scheduler --version'